# Main clock
set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
create_clock -period 9.9305 -name clk [get_ports "clk"]

# Arduino-Segment & AN
set_property PACKAGE_PIN AD21 [get_ports {AN[0]}]
set_property PACKAGE_PIN AC21 [get_ports {AN[1]}]
set_property PACKAGE_PIN AB21 [get_ports {AN[2]}]
set_property PACKAGE_PIN AC22 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]

# buzzer
set_property PACKAGE_PIN AF25 [get_ports beep]
set_property IOSTANDARD LVCMOS33 [get_ports beep]

# VGA
set_property PACKAGE_PIN N21 [get_ports {red[0]}]
set_property PACKAGE_PIN N22 [get_ports {red[1]}]
set_property PACKAGE_PIN R21 [get_ports {red[2]}]
set_property PACKAGE_PIN P21 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property PACKAGE_PIN R22 [get_ports {green[0]}]
set_property PACKAGE_PIN R23 [get_ports {green[1]}]
set_property PACKAGE_PIN T24 [get_ports {green[2]}]
set_property PACKAGE_PIN T25 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property PACKAGE_PIN T20 [get_ports {blue[0]}]
set_property PACKAGE_PIN R20 [get_ports {blue[1]}]
set_property PACKAGE_PIN T22 [get_ports {blue[2]}]
set_property PACKAGE_PIN T23 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property PACKAGE_PIN M22 [get_ports {h_sync}]
set_property IOSTANDARD LVCMOS33 [get_ports {h_sync}]
set_property PACKAGE_PIN M21 [get_ports {v_sync}]
set_property IOSTANDARD LVCMOS33 [get_ports {v_sync}]

# PS2
set_property PACKAGE_PIN N18 [get_ports PS2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_clk]
set_property PACKAGE_PIN M19 [get_ports PS2_data]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_data]

## Reset switch
set_property PACKAGE_PIN AA10 [get_ports {sw}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw}]
# set_property PACKAGE_PIN AF24 [get_ports {a[0]}]
# set_property PACKAGE_PIN AE21 [get_ports {a[1]}]
# set_property PACKAGE_PIN Y22 [get_ports {a[2]}]
# set_property PACKAGE_PIN Y23 [get_ports {a[3]}]
# set_property PACKAGE_PIN AA23 [get_ports {a[4]}]
# set_property PACKAGE_PIN Y25 [get_ports {ard_led[5]}]
# set_property PACKAGE_PIN AB26 [get_ports {ard_led[6]}]
# set_property PACKAGE_PIN W23 [get_ports {ard_led[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {a[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ard_led[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ard_led[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ard_led[7]}]